In [1]:
using Pkg
Pkg.activate("../..")

  Activating project at `~/Documents/repos/nanoOpt.jl`


In [2]:
using Measures,LazyGrids,SpecialFunctions,LaTeXStrings,Plots; plotly()

Plots.PlotlyBackend()

In [3]:
include("../../src/NanoOpt.jl")

KsspSlab (generic function with 1 method)

In [81]:
function sphere(n::Int64)
    θ = LinRange(0,π,n)
    ϕ = LinRange(-π,π,n)
    
    xA =  cos.(ϕ)*sin.(θ)'
    yA =  sin.(ϕ)*sin.(θ)'
    zA =  ones(n)*cos.(θ)'
    
    xA,yA,zA
end

function sphtable(lmax::Int64,key::String="")
    mtab = Vector{Matrix{Int64}}(undef,0)
    ltab = Vector{Matrix{Int64}}(undef,0)
    for l ∈ 1:lmax
        if key == "z"
            m = Matrix(reshape(-1:1,(1,:)))
        else
            m = Matrix(reshape(-l:l,(1,:)))
        end
        push!(ltab,Matrix(l*ones(length(m))'))
        push!(mtab,m)
    end
    ltab,mtab
end

sphtable (generic function with 2 methods)

In [99]:
lmax = 4
key="";

In [108]:
ltab,mtab = sphtable(3)
ltab,mtab = [[0;;],ltab],[0;mtab];

In [109]:
ltab

2-element Vector{Array}:
 [0;;]
 [[1 1 1], [2 2 … 2 2], [3 3 … 3 3]]

In [104]:
[0;;]

1×1 Matrix{Int64}:
 0

In [110]:
? factorial

search: factorial lfactorial logfactorial Factorization QRFactorization



```
factorial(n::Integer)
```

Factorial of `n`. If `n` is an [`Integer`](@ref), the factorial is computed as an integer (promoted to at least 64 bits). Note that this may overflow if `n` is not small, but you can use `factorial(big(n))` to compute the result exactly in arbitrary precision.

See also [`binomial`](@ref).

# Examples

```jldoctest
julia> factorial(6)
720

julia> factorial(21)
ERROR: OverflowError: 21 is too large to look up in the table; consider using `factorial(big(21))` instead
Stacktrace:
[...]

julia> factorial(big(21))
51090942171709440000
```

# External links

  * [Factorial](https://en.wikipedia.org/wiki/Factorial) on Wikipedia.


In [111]:
? big

search: big BigInt BigFloat big"" @big_str Bidiagonal KrylovJL_BICGSTAB



```
big(T::Type)
```

Compute the type that represents the numeric type `T` with arbitrary precision. Equivalent to `typeof(big(zero(T)))`.

# Examples

```jldoctest
julia> big(Rational)
Rational{BigInt}

julia> big(Float64)
BigFloat

julia> big(Complex{Int})
Complex{BigInt}
```

---

```
big(x)
```

Convert a number to a maximum precision representation (typically [`BigInt`](@ref) or `BigFloat`). See [`BigFloat`](@ref BigFloat(::Any, rounding::RoundingMode)) for information about some pitfalls with floating-point numbers.
