In [1]:
using Pkg
Pkg.activate("../..")

  Activating project at `~/Documents/repos/nanoOpt.jl`


In [2]:
using LazyGrids,Interpolations,DataFrames,CSV,SpecialFunctions,Measures,LaTeXStrings,Plots; pyplot()

Plots.PyPlotBackend()

In [3]:
include("../../src/NanoOpt.jl")

zsqrt (generic function with 1 method)

In [116]:
mat1 = material(1.0,1.0)
mat2 = material(epstable("gold"),1.0)
λ = 620.0
k₀ = 2π/λ
layer = layerstructure([mat2,mat1],[0.0,],"down");

In [117]:
green = greenreflect(layer);

In [118]:
n = 600

z = collect(LinRange(10,2000,n))

pos2 = [0*z 0*z z]
pos1 = pos2;

In [119]:
k0 = k₀

0.010134169850289655

In [120]:
green.k0 = k0
z1,zn = green.layer.z[1],green.layer.z[end]

k = [green.layer.mat[i].k(k0) for i ∈ eachindex(green.layer.mat)]
green.k1,green.kn,kmax = k[1],k[end],maximum(real.(k))

cVal = cart2pol.(pos1[:,1] - pos2[:,1],pos1[:,2] - pos2[:,2])
ϕ,ρ = first.(cVal),last.(cVal)
z,zp = pos1[:,3],pos1[:,3];

In [121]:
ind1 = z .> zn .&& zp .> zn .&& (z + zp .- 2zn) .≥ green.ratio*ρ; Index1 = findall(ind1)
ind2 = z .> zn .&& zp .> zn .&& (z + zp .- 2zn) .< green.ratio*ρ; Index2 = findall(ind2)
ind3 = z .< z1 .&& zp .> zn; Index3 = findall(ind3)

g = zeros(size(pos1,1),9)*im;

In [122]:
green.ρ,green.ϕ,green.z,green.zp = ρ[ind1],ϕ[ind1],z[ind1],zp[ind1];

In [144]:
kr = [1e-2,]
kz = green.kn
mode = "bessel"

"bessel"

In [149]:
ifun1(green,kr,mode)

600×9 Matrix{ComplexF64}:
 -0.0386515-0.00579182im  0.0+0.0im  …  0.0+0.0im  -0.0448006+0.0580673im
 -0.0385859-0.00621357im  0.0+0.0im     0.0+0.0im  -0.0454321+0.0575746im
 -0.0385158-0.00663457im  0.0+0.0im     0.0+0.0im  -0.0460581+0.057075im
  -0.038441-0.00705479im  0.0+0.0im     0.0+0.0im  -0.0466787+0.0565687im
 -0.0383617-0.00747416im  0.0+0.0im     0.0+0.0im  -0.0472936+0.0560555im
 -0.0382778-0.00789264im  0.0+0.0im  …  0.0+0.0im   -0.047903+0.0555357im
 -0.0381893-0.00831019im  0.0+0.0im     0.0+0.0im  -0.0485066+0.0550093im
 -0.0380963-0.00872674im  0.0+0.0im     0.0+0.0im  -0.0491044+0.0544763im
 -0.0379987-0.00914224im  0.0+0.0im     0.0+0.0im  -0.0496964+0.0539368im
 -0.0378966-0.00955666im  0.0+0.0im     0.0+0.0im  -0.0502825+0.0533909im
           ⋮                         ⋱             
 -0.0371028-0.0122827im   0.0+0.0im     0.0+0.0im  -0.0540259+0.0495995im
 -0.0369664-0.0126872im   0.0+0.0im     0.0+0.0im  -0.0545644+0.0490065im
 -0.0368257-0.0130901im   0.0+0.0im

600-element Vector{ComplexF64}:
 0.07953448132395963 + 0.0026153887234649244im
 0.07950117734576916 + 0.0034837879215979663im
 0.07945839201260425 + 0.004351771641230649im
 0.07940613042706775 + 0.005219236366138025im
 0.07934439882190561 + 0.006086078641990747im
 0.07927320455926368 + 0.006952195088693089im
 0.07919255612980962 + 0.007817482412712119im
 0.07910246315172036 + 0.008681837419396543im
 0.07900293636953495 + 0.009545157025283744im
 0.07889398765287321 + 0.010407338270393604im
                     ⋮
  0.0779302295157926 + 0.016107554291760067im
 0.07774968020038048 + 0.016957629739579618im
 0.07755985841452527 + 0.017805682810970874im
  0.0773607867964796 + 0.018651612366649094im
 0.07715248908763618 + 0.019495317520581496im
 0.07693499012969654 + 0.020336697652018346im
 0.07670831586170833 + 0.021175652417493463im
 0.07647249331697183 + 0.022012081762791322im
  0.0762275506198159 + 0.02284588593487933im

600×9 Matrix{ComplexF64}:
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im  …  0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im  …  0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
        ⋮                                  ⋱             
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098im  -0.0+0.0im  0.0+0.0im     0.0+0.0im  11688.2+270.224im
 5843.51+135.098

In [110]:
tm

600×9 Matrix{ComplexF64}:
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im  …  0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im  …  0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
         ⋮                               ⋱                        
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0.0im
 0.999897+0.0im  -0.0+0.0im  -0.0-0.0im     0.0+0.0im  0.0+0.0im  2.0+0